# Generated by Django 3.2.5 on 2021-07-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20210506_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboard',
            field=models.BooleanField(default=False),
        ),
    ]
