# Generated by Django 3.2.5 on 2021-08-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_user_is_onboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info_request',
            field=models.BooleanField(default=False),
        ),
    ]
