# Generated by Django 3.2.5 on 2021-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0147_category_icon_id'),
        ('account', '0052_user_info_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='users', to='product.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='distance',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_location_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
