# Generated by Django 3.2.6 on 2021-08-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20210825_0724'),
        ('account', '0054_alter_user_language_code'),
    ]

    operations = [
    ]
