# Generated by Django 3.2.6 on 2021-10-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_merge_20210826_1040'),
        ('account', '0056_merge_20210903_0640'),
    ]

    operations = [
    ]
