# Generated by Django 3.2.6 on 2022-01-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0058_alter_customerevent_type"),
        ("account", "0058_auto_20211224_1308"),
    ]

    operations = []
