# Generated by Django 3.2.6 on 2024-10-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_merge_20220104_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
