# Generated by Django 3.2.6 on 2024-10-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_user_google_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='open_id',
        ),
    ]
