# Generated by Django 3.2.6 on 2021-11-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0029_alter_payment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
