# Generated by Django 3.2.6 on 2022-09-05 09:49

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='drural_fee',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12),
        ),
    ]
