# Generated by Django 3.2.6 on 2022-09-16 09:27

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_payment_drural_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_fee",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0.0"), max_digits=12
            ),
        ),
    ]
