# Generated by Django 3.2.6 on 2022-01-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0161_auto_20211210_1501"),
        ("order", "0115_alter_order_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="product.booking",
            ),
        ),
    ]
