# Generated by Django 3.2.6 on 2022-01-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0161_auto_20211210_1501"),
        ("order", "0116_order_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="product.booking",
            ),
        ),
    ]
