# Generated by Django 3.2.6 on 2022-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '__first__'),
        ('page', '0024_alter_pagetranslation_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.ManyToManyField(to='seo.Keyword'),
        ),
    ]
