# Generated by Django 3.2.6 on 2022-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0039_auto_20220125_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
