# Generated by Django 3.2.6 on 2022-01-18 11:00

import django.contrib.postgres.indexes
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_auto_20211123_1900"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ("name",),
                "permissions": (("manage_wishlists", "Manage your own wishlists."),),
            },
        ),
        migrations.AddField(
            model_name="wishlist",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="wishlist_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="wishlist_meta_idx"
            ),
        ),
    ]
