# Generated by Django 3.2.5 on 2021-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0146_auto_20210518_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
