# Generated by Django 3.2.6 on 2021-08-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0147_auto_20210817_1015'),
        ('product', '0147_category_icon_id'),
    ]

    operations = [
    ]
