# Generated by Django 3.2.6 on 2021-09-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0149_auto_20210901_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaddress",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="product.product",
            ),
        ),
    ]
