# Generated by Django 3.2.6 on 2021-10-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0151_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
