# Generated by Django 3.2.6 on 2021-10-13 06:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0151_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productaddress",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
