# Generated by Django 3.2.6 on 2021-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0152_product_created_at"),
        ("product", "0152_productaddress_location_point"),
        ("product", "0150_collection_collection_search_gin"),
    ]

    operations = []
