# Generated by Django 3.2.6 on 2021-11-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0153_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="background_image_alt",
        ),
    ]
