# Generated by Django 3.2.6 on 2021-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_merge_20211020_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_address',
            field=models.BooleanField(blank=True, null=True, verbose_name='defaultAddress'),
        ),
    ]
