# Generated by Django 3.2.6 on 2021-10-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0154_auto_20211103_1350"),
        ("product", "0154_product_default_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="default_address",
        ),
    ]
