# Generated by Django 3.2.6 on 2021-11-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0155_remove_product_default_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_billable",
            field=models.BooleanField(default=False),
        ),
    ]
