# Generated by Django 3.2.6 on 2021-11-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0156_fraudulentproductreport_fraudulentproductreportmedia"),
        ("product", "0156_product_is_billable"),
    ]

    operations = []
