# Generated by Django 3.2.6 on 2022-01-07 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_paymentmethod"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0012_alter_company_language_code"),
        ("product", "0157_merge_20211119_1020"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookableResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("quantity_infinite", models.BooleanField(default=False)),
                ("full_day", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookable_resources",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
                "unique_together": {("name", "company")},
            },
        ),
        migrations.CreateModel(
            name="BookableResourceDailyCalendar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Fiday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        default="MONDAY",
                        max_length=20,
                    ),
                ),
                (
                    "bookable_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar",
                        to="product.bookableresource",
                    ),
                ),
            ],
            options={
                "unique_together": {("bookable_resource", "day")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="skip_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "bookable_resource_calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_periods",
                        to="product.bookableresourcedailycalendar",
                    ),
                ),
            ],
            options={
                "ordering": ("start_time",),
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.paymentmethod",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "payment_method")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(editable=False, null=True)),
                ("end_date", models.DateTimeField(editable=False, null=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=386, null=True),
                ),
                (
                    "resource_name",
                    models.CharField(blank=True, max_length=386, null=True),
                ),
                (
                    "product_sku",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bookable_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="product.bookableresource",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("product", "bookable_resource", "user"),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="payment_methods",
            field=models.ManyToManyField(
                related_name="products",
                through="product.PaymentMethodProduct",
                to="payment.PaymentMethod",
            ),
        ),
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=560)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("rating", "pk"),
                "unique_together": {("user", "product")},
            },
        ),
    ]
