# Generated by Django 3.2.6 on 2022-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0158_auto_20220107_0836"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("slug",),
                "permissions": (
                    ("manage_products", "Manage products."),
                    ("manage_product_stats", "Permission view for product stats."),
                ),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bookable",
            field=models.BooleanField(default=False),
        ),
    ]
