# Generated by Django 3.2.6 on 2021-12-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0160_auto_20220111_0910"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="BookableResource",
            options={"ordering": ("name", "pk")},
        ),
        migrations.AlterModelOptions(
            name="productrating",
            options={"ordering": ("rating", "pk")},
        ),
    ]
