# Generated by Django 3.2.6 on 2022-01-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_alter_company_options"),
        ("product", "0161_auto_20211210_1501"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="company.company",
            ),
        ),
    ]
