# Generated by Django 3.2.6 on 2022-02-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0164_auto_20220126_1211"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"permissions": (("manage_categories", "Manage categories."),)},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ("slug",),
                "permissions": (
                    ("manage_collections", "Manage product types and attributes."),
                ),
            },
        ),
    ]
