# Generated by Django 3.2.6 on 2022-02-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0165_auto_20220204_1009"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ("slug",),
                "permissions": (("manage_collections", "Manage collections."),),
            },
        ),
    ]
