# Generated by Django 3.2.6 on 2022-05-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0166_alter_collection_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=65)),
                ("title", models.CharField(max_length=65)),
                ("content", models.TextField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_email",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
