# Generated by Django 3.2.6 on 2022-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '__first__'),
        ('product', '0167_purchaseemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.ManyToManyField(to='seo.Keyword'),
        ),
        migrations.AddField(
            model_name='collection',
            name='keywords',
            field=models.ManyToManyField(to='seo.Keyword'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(to='seo.Keyword'),
        ),
    ]
