# Generated by Django 3.2.6 on 2023-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0170_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_no_price',
            field=models.BooleanField(default=False),
        ),
    ]
