# Generated by Django 3.2.6 on 2023-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0171_product_has_no_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_no_price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
