# Generated by Django 3.2.6 on 2022-04-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0031_sitesettings_default_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="dashboard_banner",
            field=models.ImageField(blank=True, null=True, upload_to="site"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="dashboard_banner_alt",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="site"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_alt",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="secondary_color",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="storefront_banner",
            field=models.ImageField(blank=True, null=True, upload_to="site"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="storefront_banner_alt",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
