# Generated by Django 3.2.6 on 2022-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0033_auto_20220413_0731"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="chatwoot_platform_api_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
