# Generated by Django 3.2.6 on 2022-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0035_shopchatwootcredentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopchatwootcredentials",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
