# Generated by Django 3.2.6 on 2022-07-28 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0037_shopgoogleanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="commission_rate",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
