# Generated by Django 3.2.6 on 2022-09-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0038_sitesettings_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='chatwoot_platform_api_key',
        ),
    ]
