# Generated by Django 3.2.5 on 2021-07-28 10:33

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0146_auto_20210518_0945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('public_name', models.CharField(max_length=100, unique=True)),
                ('cif', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('language_code', models.CharField(choices=[('ar', 'Arabic'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('bn', 'Bengali'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('es-co', 'Colombian Spanish'), ('et', 'Estonian'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('id', 'Indonesian'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('km', 'Khmer'), ('ko', 'Korean'), ('lt', 'Lithuanian'), ('mn', 'Mongolian'), ('my', 'Burmese'), ('nb', 'Norwegian'), ('nl', 'Dutch'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=35)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='companies')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='companies', to='product.category')),
                ('managers', models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('manage_companies', 'Manage companies.'),),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='company_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='company_meta_idx'),
        ),
    ]
