# Generated by Django 3.2.5 on 2021-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('ACT', 'Active'), ('DEA', 'Deactivated'), ('SUS', 'Suspended')], default='PEN', max_length=3),
        ),
    ]
