# Generated by Django 3.2.5 on 2021-08-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210803_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'permissions': (('manage_companies', 'Manage companies.'),)},
        ),
    ]
