# Generated by Django 3.2.5 on 2021-08-20 12:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210810_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=2000)),
                ('postal_code', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='company.company')),
            ],
        ),
    ]
