# Generated by Django 3.2.6 on 2021-09-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_company_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
