# Generated by Django 3.2.6 on 2021-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_company_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="is_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
