# Generated by Django 3.2.6 on 2021-11-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_companyaddress_location_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
