# Generated by Django 3.2.6 on 2021-12-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_alter_company_language_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("manage_companies", "Manage companies."),
                    ("manage_company_stats", "Permission view for company stats."),
                ),
            },
        ),
    ]
