# Generated by Django 3.2.6 on 2022-03-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0014_auto_20220126_1211"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="banner",
            field=models.ImageField(null=True, upload_to="companies/banners"),
        ),
    ]
