# Generated by Django 3.2.6 on 2022-05-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0016_auto_20220329_1134"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatwootCredentials",
            fields=[
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="chatwoot_credentials",
                        serialize=False,
                        to="company.company",
                    ),
                ),
                (
                    "user_api_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "website_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("hmac", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
