# Generated by Django 3.2.6 on 2022-05-30 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0017_chatwootcredentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwootcredentials",
            name="chatwoot_account_id",
            field=models.PositiveBigIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="chatwootcredentials",
            name="chatwoot_user_id",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="chatwootcredentials",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
