# Generated by Django 3.2.6 on 2022-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0018_auto_20220530_0737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
