# Generated by Django 3.2.6 on 2022-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0019_alter_company_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
