# Generated by Django 3.2.6 on 2022-08-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0020_auto_20220802_0908"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCredentials",
            fields=[
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stripe_credentials",
                        serialize=False,
                        to="company.company",
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="company",
            name="stripe_account_id",
        ),
        migrations.RemoveField(
            model_name="company",
            name="stripe_enabled",
        ),
    ]
